### ISSUE TITLE
Misc enhancements

### ISSUE THREAD

**Issue by mlimber** [tinfoilboy/CTML#12]
A few possible enhancements:

There are extra copies of Node objects in code like this:
```cpp
                Node& AppendChild(Node child) {
			m_children.push_back(child);
			return *this;
		}
```
This would be more efficient like:
```cpp
                template<class T>
                Node& AppendChild(T&& child) {
			m_children.push_back( std::move(child) );
			return *this;
		}
```
Likewise `_CountOccurrences(std::string finder, const std::string& findable)` and `_ParseClassesAndIDS(std::string classesAndIDs)` appear to be able to take a const ref to string to avoid a copy.

Depending on which C++ standard you are supporting, you could also accept `std::string_view` instead of `std::string` in your interface, which may avoid copies.

I also notice you have used names that are reserved for the implementation when you name things with an underscore and capital letter like `_GetFormattedContent`, which means it's technically undefined behavior.

**Comment by tinfoilboy** [comment]
This should be fixed with 0b8ba53.

I believe I want to support C++11 as that was the initial goal of the library, thus I don't believe I can use a `std::string_view`. However, I think your other concerns should be addressed.
