### ISSUE TITLE
Support non-closing tags such as <meta>

### ISSUE THREAD

**Issue by torbjoernk** [tinfoilboy/CTML#14]
There are some HTML tags, which do not have a closing tag. For example the `<meta>` tag below is valid:
```
<meta charset="UTF-8">
```
While CTML
```
CTML::Node{"meta"}
  .SetAttribute("charset", "UTF-8")
  .ToString(CTML::Readability::SINGLE_LINE)
```
outputs
```
<meta charset="UTF-8"></meta>
```
This is invalid HTML and parsers do not need to deal with it correctly.

**Comment by tinfoilboy** [comment]
This is a current feature in the library, though I might not have documented it. If you add `.UseClosingTag(false)` on the Node instance it should omit the closing tag.
