### ISSUE TITLE
Tests fail as they expect std::map providing a sorted iterator (which is doesn't)

### ISSUE THREAD

**Issue by torbjoernk** [tinfoilboy/CTML#15]
When running the tests, one may get (at least on my machine with GCC 8.2)
```
No Close Test failed!
Node Output: <img alt="Hilarious image" src="funnypicture.png">
Expected Output: <img src="funnypicture.png" alt="Hilarious image">
```
Because of this
https://github.com/tinfoilboy/CTML/blob/0eb16c35c591f990db32d41c58bce71d41817b8c/CTML/Node.h#L99-L101
and this
https://github.com/tinfoilboy/CTML/blob/0eb16c35c591f990db32d41c58bce71d41817b8c/CTML/Node.h#L200-L201
and its usage at
https://github.com/tinfoilboy/CTML/blob/0eb16c35c591f990db32d41c58bce71d41817b8c/CTML/tests.cpp#L87-L88

I'm not sure, whether someone actually wants the attributes serialized in the same order they were defined. Otherwise, the unit tests needs to be adjusted.

**Comment by tinfoilboy** [comment]
Rewrote the tests so this issue no longer applies.
