### ISSUE TITLE
SetContent not working

### ISSUE THREAD

**Issue by TheFox** [tinfoilboy/CTML#19]
First, thank you for the clean rewrite of 1.0.0. This broke everything in my code. ;D

I have now another issue. I'm using 0b8ba531 (currently latest) commit.

While

```c++
CTML::Node tableRow{"tr"};
tableRow.AppendChild(CTML::Node("td", "my_content1"));
```

works, the following doesn't work anymore:

```c++
CTML::Node tableRow{"tr"};
tableRow.AppendChild(CTML::Node("td").SetContent("my_content2"));
```

In the first example `my_content1` is the content, like expected, while in the second the call of `SetContent` will not set the string as content.

It's not actually a problem, since the first code does the job perfect. But maybe some legacy code will break.

**Comment by tinfoilboy** [comment]
That is intended behavior for the future. Using `SetContent` only allowed
for one piece of text per Node which is against the HTML spec.

Thus, the new recommended way is to use `AppendContent(std::string)`,
depending on where you want your text node to appear. If you need to edit
the text, you can grab it as a child at the position you appended it and
edit the content of that Node with `SetContent`.
