### ISSUE TITLE
Check for "content" instead of "m_content" in first constructor

### ISSUE THREAD

**Issue by ecampostrini** [tinfoilboy/CTML#21]
Pls correct me if I'm wrong but I think that the following line should be checking for `content` instead of `m_content`
https://github.com/tinfoilboy/CTML/blob/64a1606d92fa0bac26190648dbf82e46c9ad7e63/include/ctml.hpp#L118

**Comment by tinfoilboy** [comment]
You are correct. Will fix soon.
