### ISSUE TITLE
Add support for AppendNodeToFooter()

### ISSUE THREAD

**Issue by danielpatenaude** [tinfoilboy/CTML#22]
It would be nice to be able to add to a footer as AppendNodeToHeader and AppendNodeToBody work.

**Comment by danielpatenaude** [comment]
I actually just fixed this issue, but I can't open a PR for it :). I guess I'll make a fork instead?

**Comment by tinfoilboy** [comment]
Unfortunately, this would also be out of the scope of the library, as `AppendNodeToHead` is to append elements to the `<head>` element of the document, which is for the metadata of the HTML document, and `AppendNodeToBody` is strictly for the `<body>` element of the document which is for the content that will be rendered on the browser.

Adding a `<footer>` element to the `Document` class would, to me, be trying to control what the programmer's layout for their document would be. Which is something that I do not want to do.

I do appreciate the suggestion though!
