### ISSUE TITLE
Implement selectors to get child nodes

### ISSUE THREAD

**Issue by tinfoilboy** [tinfoilboy/CTML#26]
Getting children from a Node currently has to be done by either iterating the children or knowing the index of the child that you wish to grab. It may be beneficial to add functionality to grab these children via the selector parsing that is already in the library for creating elements from abbreviations. This would then allow for more flexibility in modifying existing structures and closer mimic the methods used for getting elements in the browser.

**Comment by Codes97** [comment]
It would be great if the way to query childrens is improved. Do you plan to implement this in a near future?

**Comment by tinfoilboy** [comment]
Hey @Codes97! My apologies for the late response, I've been pretty busy with work and life things. However I found some time recently and implemented selector search mimicking `querySelectorAll` in browser JavaScript with the `CTML::Node::QuerySelector(const std::string&)` method.

This is implemented in the [2.0.0](https://github.com/tinfoilboy/CTML/releases/tag/2.0.0) release, or in commit 8076165. Hope this is what you had in mind 🙂
